### ISSUE TITLE
https://www.chatbotui.com/ no longer works?

### ISSUE THREAD

**Issue by bartholomewbartkowski** [mckaywrigley/chatbot-ui#1063]
I haven't checked in at https://www.chatbotui.com/ in a while. Today I noticed that chatbotui has not chat bot or UI :/

<img width="1422" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/107932776/208e858c-ab1a-499a-a094-0ef082c95b37">

Any ideas if something's changed here?

**Comment by akhilam512** [comment]
+1 was quite convenient to just visit a hosted version :)

**Comment by Miwitom** [comment]
+2!

**Comment by jarrenrocks** [comment]
I had it pinned and used it daily. Once 1 click to vercel is up I'll use that instead I think, but the easy access was great for sharing with people because it was a great tool

**Comment by VladislavAntonyuk** [comment]
you can use https://yakgpt.vercel.app/

**Comment by jarrenrocks** [comment]
That's okay for the time being, but honestly it doesn't really solve for my use case. 
I have a lot of custom prompts that I use on a regular basis. Honestly I was surprised when Chatbot UI went down because I didn't see a notification and now my prompts are gone.

There wasn't a warning except on the GitHub repo, and I hadn't checked that in months, though that sort of deviates from the purpose of this thread, which is specifically to discover if a hosted version will be returning.

**Comment by VladislavAntonyuk** [comment]
@jarrenrocks you can retrieve your prompts from localStorage

**Comment by mckaywrigley** [comment]
A data export was meant to be automatically triggered. I’ll fix this bug.

As far as a hosted version you can expect that next week, though it will be $10/mo.

The cloud bill at this point is just too much to be free. While inference is paid for by the user, we pay for hosting, storage, edge function usage, etc.

**Comment by ghost** [comment]
you can use [https://apiskey.com/](https://apiskey.com/)

**Comment by Somnus1437** [comment]
> 您可以使用https://apiskey.com/

it can’t be used
