### ISSUE TITLE
GPT-4 not working for me on Vercel Hosted Version

### ISSUE THREAD

**Issue by Doscadesa** [mckaywrigley/chatbot-ui#1082]
Hi, 

First of all, thanks for your amazing work. 
This issue is probably based on my lack of skill but cannot find what is the real problem here. 

I have followed the steps 1 by 1 and I have finally gotten the hosted fronted to work and apparently is connected to supabase because is allowing me to log in with the user I have created in supabase. 

Problem is that backend seems to be not connected to frontend in the rest of aspects. 

Whatever I do is not working. 
If I click on the right "GPT-4 Turbo" a void black space appears below but cannot interact. 
If I write something in the chat is not appearing above as writen. 
Same happens when trying to open a new chat, open a new config, etc. 

![image](https://github.com/mckaywrigley/chatbot-ui/assets/128645496/c68ff8c0-c72d-46d8-a59e-85cb25b2201e)

This is the log when writing a text or trying to add a file. 

![image](https://github.com/mckaywrigley/chatbot-ui/assets/128645496/a7278a64-355f-41b0-b555-0bde713d5606)

**Comment by diallo-bocar** [comment]
Hi @Doscadesa,

Firstly, it's great to hear that you've got your front end up and running and connected to Supabase. These kinds of integration issues can be quite tricky, so don't worry—it often just takes a bit of troubleshooting to sort out.

From what you've described, it sounds like the communication between your backend and frontend isn't fully configured. This is a common hurdle, and I had a similar issue which turned out to be due to my Supabase configuration.

Here are a few steps to check:

**Supabase Configuration**:

Ensure that all necessary tables have been created in Supabase. Sometimes, missing a step in the initialization scripts can lead to such issues.
In your migrations script (**20240108234540_setup.sql**), double-check that you've replaced the **project_url** and **service_role_key** with your specific project details from Supabase.

**Supabase Integration on Vercel**:

Confirm that the environment variables in your Vercel app match the necessary values for Supabase exactly. Any discrepancy here could disrupt the connection.


I hope these suggestions help you get to the bottom of the issue. Keep us updated, and don't hesitate to ask for more help if needed. Good luck!

**Comment by Doscadesa** [comment]
Thanks for your quick reply. 

I have rechecked the terminal where I have loaded the supabase configuration and no errors present so I guess every table has been created locally and then transfered to supabase web. 

Regarding the -540_setup.sql below a parcial picture of the project & service_role 
![image](https://github.com/mckaywrigley/chatbot-ui/assets/128645496/6a422b9b-5db1-4f61-bab1-7ccd6c5ac59f)

This was my main doubt. 
The readme as is writen is mentioning that you should use the supabase status given data for the project_url but I guess that I should be using the project_url that supabase web is providing. 
In any case I have tried both options and none of them are working. 

And finally regarding the 3 environment variables for Vercel, these are correct. 
First copied&pasted and then automatically synced by integrating the supabase service into the vercel project. 

I have done the process twice from the beginning.

**Comment by diallo-bocar** [comment]
You're welcome.

Since you've confirmed that the tables are created and the environment variables on Vercel are correct, let's delve a bit deeper:

**Project URL Clarification**:

The project_url should typically be the endpoint provided by Supabase (just as you shown screenshot) which you can find in your Supabase project's API settings. 

**Error Logs:**

Since the setup seems correct, examining the error logs in more detail could provide some insight. Are there any specific error messages in your Vercel deployment logs or browser console when you attempt to interact with the backend? 

Lastly, there is a new update from this repository so you can check and see it can help. 


Here is a [Try this one - issue related to Vercel deployment ](https://github.com/mckaywrigley/chatbot-ui/issues/1058). I tried it and it worked. You can find a repository with the differents steps to follow.
