### ISSUE TITLE
No access to Ollama in windows 11 (WSL2) 

### ISSUE THREAD

**Issue by mivanovitch** [mckaywrigley/chatbot-ui#1083]
The Ollama server is running correctly. No trouble to install everything.   
But always the same error message when launching chatbotUI 

![Capture d'écran 2024-01-10 144548](https://github.com/mckaywrigley/chatbot-ui/assets/99186457/a6abf98c-605d-4b4d-82a2-b0b9389a5848)

**Comment by diallo-bocar** [comment]
Hi @mivanovitch,

The error message indicates that the ollama command isn't recognized. This typically happens when the command isn't installed globally, isn't included in the system's PATH, or is intended to be run in a different environment (like Windows Subsystem for Linux - WSL).

Here are some steps to troubleshoot this issue:

**Check the Environment:**

Ensure that you're running the application in the correct environment where the ollama command is installed. If it's meant to be run inside WSL, make sure you're not accidentally executing it in the standard Windows command line.

**Review the Code:**

As per the code in route.ts at [app/api/localhost/ollama/route.ts](https://github.com/mckaywrigley/chatbot-ui/blob/main/app/api/localhost/ollama/route.ts#L9), it seems like the application is trying to execute a command using exec. Confirm that the command is correct and that it works when run directly in your environment's terminal.

**Consider Code Changes:**

You could check out the pull request at [PR](https://github.com/mckaywrigley/chatbot-ui/pull/1062), which may have a workaround or a fix that doesn't require using exec to call ollama.

I hope these suggestions help you resolve the issue.

**Comment by mckaywrigley** [comment]
Give it a run with the new changes from the most recent PR.

**Comment by mivanovitch** [comment]
It's better with the most recent PR indeed.  

But ECONNREFUSED error. (Not such error when using WEBUI with Ollama so it's not a problem with Ollama on WSL2 as I was first thinking)    

![Capture d'écran 2024-01-10 171035](https://github.com/mckaywrigley/chatbot-ui/assets/99186457/06ce1f23-2a6b-4344-958d-c0e4b66f36fc)

**Comment by wrapss** [comment]
have you defined NEXT_PUBLIC_OLLAMA_URL in your environment file?

**Comment by mivanovitch** [comment]
will check thanks !

**Comment by mivanovitch** [comment]
Sorry for the delay : yes for NEXT_PUBLIC_OLLAMA_URL
