### ISSUE TITLE
Non-localhost use and File Upload Failures

### ISSUE THREAD

**Issue by A8IO** [mckaywrigley/chatbot-ui#1113]
I have chatbot-ui running on my local network at  `192.168.100.10:3000`.  Getting this working has required changing localhost/127.0.0.1 references to the externally facing IP address in the following config files:

.env.local
```
NEXT_PUBLIC_SUPABASE_URL=http://192.168.100.10:54321
```

config.toml
```
[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://192.168.100.10:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://192.168.100.10:3000"]
```

Whilst this approach basically works (account setup, login and chat with Azure OpenAI works):
- Chat with files upload is failing (Error: JSON object requested, multiple (or no) rows returned)
- I cant change the chat model in the top right drop down LLM selector
- This approach opens up the Supabase backend management interface on `http://192.168.100.10:54323/` without any authentication requirements.  Not ideal as users can be deleted etc.

The use case here is to run everything on the local network (not on Supabase Cloud).  Is there a preferred configuration to run chatbot-ui when we have a use case where we do not want to run it purely on localhost?

**Comment by amir-ghasemi** [comment]
> * Chat with files upload is failing (Error: JSON object requested, multiple (or no) rows returned)

Having this file upload issue with the default settings as well. Seems to be a problem with file uploads in general.

**Comment by DobsX** [comment]
I noticed the file upload error message is generic.  If you change this to raise the error message instead it may provide more information:

https://github.com/mckaywrigley/chatbot-ui/blob/51131c2e1d1ff925699d98db505a3a3e55ceba98/components/chat/chat-hooks/use-select-file-handler.tsx#L188

`toast.error(error)`

In my case, I was uploading files over 10mb which returned an error, but the genric-ness made it hard to understand what the issue is/was.

Perhaps also related to your issue.

**Comment by iancaseydouglas** [comment]
I run mine in a container and expose it to the local network on port 80 with an actual service name. This also has the benefit of squashing IPV6, otherwise, dev only listens on IPV6 localhost and not IPV4 localhost. Be sure to add a flag to your docker run command with the network name the supabase containers are using, which you can find with docker inspect or via the docker desktop gui.
Map a volume into your container for data and add there ya go.
.
To lock down your backend, put it behind a firewall or reverse proxy.

Whatever you do, Don't hardcode IP addresses
