### ISSUE TITLE
supabase start gets an EOF error with the migration phase

### ISSUE THREAD

**Issue by JesseGuerrero** [mckaywrigley/chatbot-ui#1120]
I get EOF exception in Arch Linux when following the instructions
![image](https://github.com/mckaywrigley/chatbot-ui/assets/27308928/c23aaaad-7529-49e1-b812-52cd133c8677)

Tips?

**Comment by mrmisor** [comment]
Have you solved this problem? I've also encountered this problem.

**Comment by mrmisor** [comment]
I solved this problem.
1. supabase start without migrate
2. in "supabase_db_chatbotui" Container reinstall the vector extension
3. run migrate

**Comment by BastLast** [comment]
> I solved this problem.
> 
>     1. supabase start without migrate
> 
>     2. in "supabase_db_chatbotui" Container reinstall the vector extension
> 
>     3. run migrate

can you explain more im facing the same issue ...

**Comment by mrmisor** [comment]
> > I solved this problem.
> > ```
> > 1. supabase start without migrate
> > 
> > 2. in "supabase_db_chatbotui" Container reinstall the vector extension
> > 
> > 3. run migrate
> > ```
> 
> can you explain more im facing the same issue ...

I encountered this issue because there was an error when enabling vector extension. You can refer to the file 20240108234540_setup.sql under the directories [chatbot-ui](https://github.com/mckaywrigley/chatbot-ui/tree/main)/[supabase](https://github.com/mckaywrigley/chatbot-ui/tree/main/supabase)/[migrations](https://github.com/mckaywrigley/chatbot-ui/tree/main/supabase/migrations). After testing, I found that there is an issue with the default installation of vector extension. I deleted the migrations file first, let Supabase run, then entered the Docker container, reinstalled the extension, and copied the migrations file back. Finally, I executed the "supabase migrate up" operation.

**Comment by bplenderleith** [comment]
> I encountered this issue because there was an error when enabling vector extension. You can refer to the file 20240108234540_setup.sql under the directories [chatbot-ui](https://github.com/mckaywrigley/chatbot-ui/tree/main)/[supabase](https://github.com/mckaywrigley/chatbot-ui/tree/main/supabase)/[migrations](https://github.com/mckaywrigley/chatbot-ui/tree/main/supabase/migrations). After testing, I found that there is an issue with the default installation of vector extension. I deleted the migrations file first, let Supabase run, then entered the Docker container, reinstalled the extension, and copied the migrations file back. Finally, I executed the "supabase migrate up" operation.

I'm having the same issue. Can you provide more detail on how you reinstalled the vector extension in the docker container? I've tried to open up a shell for the "supabase_db_chatbotui" container and can't figure out how to reinstall the pgvector extension within the container. I tried following the installation steps from the [pgvector repo](https://github.com/pgvector/pgvector?tab=readme-ov-file#installation) but didn't have any luck.
