### ISSUE TITLE
Switching between Hosted models are not possible when using Azure OpenAI

### ISSUE THREAD

**Issue by othmanelhoufi** [mckaywrigley/chatbot-ui#1194]
Hi,

After adding Azure OpenAI key/endpoint and models names, the interface doesn't allow to switch between GPT-4-Turbo or GPT-4-Vision or GPT-3-Turbo, its blocked on the only selected model which is GPT-4-Turbo. See pictures bellow.

<img width="624" alt="Screenshot 2024-01-16 at 15 14 23" src="https://github.com/mckaywrigley/chatbot-ui/assets/40344016/b3a1df3e-3e01-4fe4-a323-2dabff61ecb1">
<img width="1467" alt="Screenshot 2024-01-16 at 15 14 57" src="https://github.com/mckaywrigley/chatbot-ui/assets/40344016/b204c00c-a035-49df-98ea-95894e498e3a">

**Comment by gijigae** [comment]
It seems to me there might be something wrong with the way you setup Azure OpenAI environment variables. You're supposed to see the OpenAI icons instead of those lock icons. In the image below, I have lock icons since I have not setup the API key for Gemini. Please double check your settings for Azure OpenAI. Hope it helps.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/81459/8f9060d3-1673-477e-8396-31a434c9e8c9)

**Comment by mckaywrigley** [comment]
Fixed!
