### ISSUE TITLE
Have error 500

### ISSUE THREAD

**Issue by PhanTrongGiap** [mckaywrigley/chatbot-ui#300]
![image](https://user-images.githubusercontent.com/9209282/228749174-88851495-537b-44d0-a89a-b52699e752a6.png)

**Comment by PhanTrongGiap** [comment]
![image](https://user-images.githubusercontent.com/9209282/228749931-d33add17-f920-4342-add3-abd8638abad0.png)

**Comment by foxfog** [comment]
This model's maximum context length is 4097 tokens, however you requested 5360 tokens (3960 in your prompt; 1 400 for the completion). Please reduce your prompt; or completion length.

Is the dialogue long? I have the same. It sends all previous messages to the request at once and the number of tokens exceeds 4000. Probably some functionality needs to be done so that the bot breaks old messages into chunks and saves a "short retelling" somewhere for the next request
![Screenshot_1](https://user-images.githubusercontent.com/11442544/228789178-5b0497a7-64d2-4896-af29-303870718d83.jpg)
