### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by PhanTrongGiap** [mckaywrigley/chatbot-ui#307]
Does anyone have it like me. After about 1-6 hours of running, I will get this error and have to close the old screen session to turn it back on.

```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

**Comment by kaaboaye** [comment]
It seems like your server died and didn’t restart.

**Comment by PhanTrongGiap** [comment]
I've got a workaround. But still don't know the reason.
Now, instead of running
`npm run dev`
  then i run
```
npm run build
npm run start
```

Then I see that phenomenon is no more.

**Comment by PhanTrongGiap** [comment]
> 

Server is not dead, still running normally =))

**Comment by mharini** [comment]
The 503 issue occurring to me when I am running the applicaiton in AWS instance. 

Solution: https://github.com/mckaywrigley/chatbot-ui/blob/main/utils/server/index.ts -> Line 103
Instead of controller.error just have console.error so that it won't exit the running applicaiton to throw 503 or 504 error.
