### ISSUE TITLE
GPT-4 is not actually GPT-4

### ISSUE THREAD

**Issue by zain** [mckaywrigley/chatbot-ui#402]
I have access to GPT-4 via the API, but even when I select GPT-4 in the dropdown, it still seems to be GPT-3:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/4229/229652288-6642e91d-ba51-46b9-975a-15a6895a09f8.png">

I suspected this is the case, because ChatbotUI is actually much faster than GPT-4 has been for me so far. 

In the official UI, for comparison:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/4229/229652303-d41adf5a-0f57-4e4b-bf9b-75377735c970.png">

**Comment by jponline77** [comment]
GPT is not very aware of itself.  Don't trust GPT answers about itself.

**Comment by falling-springs** [comment]
@zain Given how these models are trained, you can't expect them to accurately identify the base model being used. Neither GPT-3.5 nor GPT-4 "know" what model they are based on. 

For the most part, responses to questions like this one will refer to the system prompt. For chatbot-ui, the default system prompt is: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown." Because the system prompt mentions ChatGPT, the model will refer to ChatGPT, but it doesn't really know anything else about itself.

(Also you can always check which model you're making calls to by looking at your usage at platform.openai.com)

**Comment by zain** [comment]
That's reasonable. Thanks for the info! I closed the issue.

**Comment by ItwithYou** [comment]
Hi, can you guys guide me about how to deploy to website without asking API
Thanks
