### ISSUE TITLE
500 Error => https://www.chatbotui.com/api/chat

### ISSUE THREAD

**Issue by aydinkazim** [mckaywrigley/chatbot-ui#413]
<img width="1440" alt="Screenshot 2023-04-04 at 15 42 24" src="https://user-images.githubusercontent.com/53534245/229796300-f5737ce1-c335-44f3-a724-905440530160.png">

**Comment by thegitfather** [comment]
same

wondering if my initial free credit already expired, but I guess it would not respond with a `500` if this is the case, right?

![image](https://user-images.githubusercontent.com/3913533/229834090-565f6b4d-305a-4dc7-ae4d-1e35d142284a.png)

**Comment by steven2358** [comment]
Same here. It's not the credit.

**Comment by esafirm** [comment]
I also got this error.
Here's the API request

```json
{
  "model": {
    "id": "gpt-3.5-turbo",
    "name": "Default (GPT-3.5)"
  },
  "messages": [
    {
      "role": "user",
      "content": "Is it working now"
    },
    {
      "role": "user",
      "content": "is it working now?"
    }
  ],
  "key": "****",
  "prompt": "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
}
```

 The API response is just `Error` 

---

Anyway, @thegitfather where can I check the free credit for the API?

Update: nvm, already got the link: https://platform.openai.com/account/usage

**Comment by PhanTrongGiap** [comment]
This error is caused by the token limit per conversation. Sent error, waiting for admin to fix

**Comment by esafirm** [comment]
Mine actually happened because the trial credits are expired.
I think it's the same as @thegitfather 

After upgrading to paid account, the 500 is gone.

**Comment by aydinkazim** [comment]
we need to know if trial credits have expired

<img width="813" alt="Screenshot 2023-04-07 at 16 42 53" src="https://user-images.githubusercontent.com/53534245/230618927-8456e356-401e-4bae-a052-58e01c7479de.png">

**Comment by s10mcow** [comment]
yes confirm - u need to upgrade to a paid account - just add a credit card.

**Comment by steven2358** [comment]
I am on a paid account and it still happens. In an earlier reply @PhanTrongGiap wrote:

> This error is caused by the token limit per conversation. Sent error, waiting for admin to fix

and I have verified that that is indeed the case for me.

**Comment by jairodriguez** [comment]
I`m on paid account. 
The problem is exceeding the token max per conversation. 
As I understand the openai chatbot cuts the conversation context in order to avoid running into this problem and keep the conversation going indefinitely, however the drawback is losing the context from the earlier part of the conversation, one has to remind the chatbot what was spoken about previously. 

The solution is embeddings with vector database. This could be hardcoded into the bot or as a plugin:

1.Divide your long text into small chunks that are consumable by GPT
2.Store each chunk in the vector database. Each chunk is indexed by a chunk embedding vector
3.When asking a question to GPT, convert the question to a question embedding vector first
4.Use question embedding vector to search chunks from vector database
5.Combine chunks and questions as a prompt, feed it to GPT
6.Get the response from GPT

<img width="1152" alt="Screenshot 2023-04-07 at 14 47 31" src="https://user-images.githubusercontent.com/73152066/230677684-894d247f-b061-447c-a00b-df340823a680.png">

<img width="1418" alt="Screenshot 2023-04-07 at 14 49 27" src="https://user-images.githubusercontent.com/73152066/230677647-4bcd9529-56f6-4085-b095-19ca5b4551c3.png">
