### ISSUE TITLE
Bug - when searching for a prompt/conversation, they will all dissapear

### ISSUE THREAD

**Issue by erickosanchezj** [mckaywrigley/chatbot-ui#511]
Sometimes when using the search bar for a prompt or a conversation, they will no longe return results and will display none

![Search clearing out](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTQ0NDY5ZmE0YWJiMDBlZjg4N2Q3NGQyNDJiNjBkNDIwOThjNmY3OSZjdD1n/pkZpnG7oqbDHMTlkfC/giphy.gif)

After refreshing the page, conversations and prompts are back

**Comment by DeceptiveScorpion** [comment]
Steps to to replicate the bug.

Expected behavior:  You should be able to clear what you're searching if no results are found.

Observed behavior: Once this bug occurs you must refresh the page to be able to search again.

Steps to replicate:

1. Type text into either the `chat search box `or the `prompt search box` until results no longer show.
