### ISSUE TITLE
Google Search Plugin doesn't work when prompted

### ISSUE THREAD

**Issue by jayscambler** [mckaywrigley/chatbot-ui#565]
Having an issue getting Chatbot to recognize that it can search using Google

**Comment by erbanku** [comment]
Same here, error message:
`Application error: a client-side exception has occurred (see the browser console for more information). `
This error seems to be because of Next.js https://github.com/vercel/next.js/issues/43772
![image](https://user-images.githubusercontent.com/79493862/232177597-392557b5-8548-4839-8a45-b481390e0ff9.png)

**Comment by geekbb** [comment]
<img width="861" alt="CleanShot 2023-04-15 at 20 51 26@2x" src="https://user-images.githubusercontent.com/46196358/232224750-23cd7c70-a0af-4d0d-9a68-2a89ecfede53.png">

**Comment by geekbb** [comment]
<img width="861" alt="CleanShot 2023-04-15 at 20 51 26@2x" src="https://user-images.githubusercontent.com/46196358/232224767-1dbd662c-cdce-48c9-a204-b1af65b53242.png">

Local deployment is the same

**Comment by Designdocs** [comment]
#502
