### ISSUE TITLE
Selecting GPT-4 model does not work, the AI identifies as GPT-3 when prompted.

### ISSUE THREAD

**Issue by Diae-Louali** [mckaywrigley/chatbot-ui#681]
![image](https://user-images.githubusercontent.com/68733422/235387669-de0a90f2-06e6-41bf-88ab-19fb30ac7b35.png)

I followed the basic installation steps in the documentation. I also do have access to GPT-4 API.

**Comment by jmagly** [comment]
this is normal GPT-4 is the same dataset as GPT-3. it was not changed simply refined. Gpt will also claim its 4 and ive seen it also claim its v5.6

**Comment by Diae-Louali** [comment]
I have a chatGPT plus subscribtion, this is it's response every time I ask GPT 4 the question : 
![image](https://user-images.githubusercontent.com/68733422/235443030-e4d5d7f2-4374-4e11-b93c-728d329b3c70.png)

**Comment by jmagly** [comment]
ChatGPT != the gpt-4 api. they both use the same model but

1. ChatGPT uses a gateway and clearly sends its own bias map with each request
2. its more heavily moderated

The model is based on GPT-3 dataset and it had to be "told" it was 4. I bet its in thier system prompt now because people have been saying this same thing for a month. Its not new. 

Honestly, with the changes OpenAI made just this weekend, its no longer viable to A|B test between the API and ChatGPT, they are now too different.

**Comment by Diae-Louali** [comment]
Great, thanks for the clarification.
