### ISSUE TITLE
Should have given credit at least.

### ISSUE THREAD

**Issue by shashicpontentwriter** [mckaywrigley/chatbot-ui#689]
These guys at https://team-gpt.com/ are using the same open script chatbot-ui, but they did not give credit. They should have at least mentioned it.

**Comment by kachar** [comment]
Thank you for bringing this to our attention, @shashicpontentwriter.

We at Team-GPT greatly appreciate the open-source community and the valuable work done by the creators of projects like Chatbot-UI. In fact, we have acknowledged the use of Chatbot-UI in our Terms of Use page, where we have provided appropriate credit to the original authors and contributors.

While it's true that we have utilized elements from Chatbot-UI in our initial MVP, our product has since evolved significantly, incorporating new features and functionality, including collaboration capabilities not present in the original project. Nonetheless, we remain grateful for the foundational work provided by Chatbot-UI and its developers.

Once again, we appreciate your vigilance in ensuring that open-source projects are given proper credit. We are committed to supporting and fostering the open-source community, and we will continue to recognize the contributions of the projects and individuals that have played a role in our development.

We value the open-source community and always strive to follow best practices when it comes to giving credit and complying with licensing requirements. If you have any further concerns or suggestions, please feel free to let us know.

**Comment by shashicpontentwriter** [comment]
> Thank you for bringing this to our attention, @shashicpontentwriter.
> 
> We at Team-GPT greatly appreciate the open-source community and the valuable work done by the creators of projects like Chatbot-UI. In fact, we have acknowledged the use of Chatbot-UI in our Terms of Use page, where we have provided appropriate credit to the original authors and contributors.
> 
> While it's true that we have utilized elements from Chatbot-UI in our initial MVP, our product has since evolved significantly, incorporating new features and functionality, including collaboration capabilities not present in the original project. Nonetheless, we remain grateful for the foundational work provided by Chatbot-UI and its developers.
> 
> Once again, we appreciate your vigilance in ensuring that open-source projects are given proper credit. We are committed to supporting and fostering the open-source community, and we will continue to recognize the contributions of the projects and individuals that have played a role in our development.
> 
> We value the open-source community and always strive to follow best practices when it comes to giving credit and complying with licensing requirements. If you have any further concerns or suggestions, please feel free to let us know.

Thank you for taking the time to read and respond to my message. I'm glad to hear that you appreciate my commitment to supporting and giving credit to open-source projects.

I understand that using open-source software for business or personal purposes can be a great way to save time and money while also benefiting from the contributions of the wider community. As you mentioned, it's essential to give credit to the original authors and contributors, as well as comply with any licensing requirements.

I'm glad to hear that you appreciate my efforts to acknowledge the contributions of the creators of Chatbot-UI and other open-source projects. I believe that recognizing the efforts of the community is an essential part of supporting and fostering the growth of open-source software.

Once again, thank you for your response, and I appreciate your support for open-source projects.

**Comment by reconrad48** [comment]
From I can tell, this team-gpt is an online saas, only uses 3.5-turbo, and somehow interfaces with OpenAi so that it handles billing and invoices? I am confused about team-gpt handing the the invoicing and billing.

**Comment by kachar** [comment]
Hi @reconrad48,

We're rolling out GPT-4 support today so this won't be a problem for organizations with access to GPT-4 model over the OpenAI API. The ones that do not have access can [join the waitlist here](https://openai.com/waitlist/gpt-4-api).

As for the billing - OpenAI charges individuals and organizations according to their [terms and pricing](https://openai.com/pricing#language-models).
Team-GPT only uses the provided API key to communicate with the selected model. We don't have access to the usage statistics and we don't need one, that's entirely between OpenAI and the customer.

Team-GPT is provided as a collaborative AI  workspace shared between team members so they can work and learn together, instead of on their own.

![image](https://user-images.githubusercontent.com/893608/236246403-ddb1db49-1874-4ff2-9b37-bd31d4626ce9.png)

**Comment by Jdban** [comment]
@kacher y'all might want to change your tool's name

https://openai.com/brand

![image](https://user-images.githubusercontent.com/490005/236351559-cbc36b44-8544-44c3-9d6d-57426f2f2a13.png)
