### ISSUE TITLE
Why is it calling api/models of the localhost?

### ISSUE THREAD

**Issue by Victor-Cooper** [mckaywrigley/chatbot-ui#833]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/22309253/a9482f6d-2dac-4d13-b9da-1025fe5af923)
As the picture shown. Does anyone know why is it calling a localhost api and how to fix it?

**Comment by mozeryansky** [comment]
https://github.com/mckaywrigley/chatbot-ui/blob/main/pages/api/models.ts

You should never expose an API key publicly. Instead of calling OpenAI from the client using your private key, you need to use an edge function which has access to the private key.

I'll guess it's because you haven't set the OPENAI_API_KEY environment variable. The reason will be in the response body, or the console log.

**Comment by cylqinsmoon** [comment]
I have the same confusion and I set the environment variables NEXT_PUBLIC_OPENAI_API_KEY and NEXT_PUBLIC_OPENAI_API_HOST, and I am getting a console printout of process.env.NEXT_PUBLIC_OPENAI_API_KEY and process. env.NEXT_PUBLIC_OPENAI_API_HOST have taken effect and the original process.env.OPENAI_API_KEY and process.env.OPENAI_API_HOST have been changed to the corresponding NEXT_PUBLIC_ prefixes
