### ISSUE TITLE
Is it divided into frontend and backend?

### ISSUE THREAD

**Issue by damc** [mckaywrigley/chatbot-ui#835]
I'm confused. When I go to https://www.chatbotui.com/ I can see in the developer tools that it sends a request to something like chatbotui.com/api/chat with my API key which suggests that it has frontend (user interface) and backend (API responsible for communicating with OpenAI API). But when I look at the code in the repository, it looks more like there is only frontend and the frontend directly communicates with OpenAI API. So, how does it work? Does it have frontend and backend or not?

If I want to run this chatbot with my API key and hide that API key from users, can I do that?

**Comment by ghost** [comment]
You are using the online hosted version that's why, if you want to have it self hosted (running on you laptop) then you have to download and run the code on you machine.

The one you are using is hosted online, which means it acts a website, you are viewing the frontend, and there is also a backend. But if you download and run on your machine, then you are both.

**Comment by markNZed** [comment]
Is there a clear (ideally specified) API between the frontend and the backend ? It would be nice to use the frontend in an existing project and "map" the existing backend onto this frontend.
