### ISSUE TITLE
This repo _seems_ abandoned

### ISSUE THREAD

**Issue by jaimejim** [mckaywrigley/chatbot-ui#909]
As this repo seems to be abandoned by the author since 20th April , could someone point here to an advanced fork?
Thanks to the author in any case btw!

**Comment by Nils-22** [comment]
I think this is the most developed one currently: https://github.com/dotneet/smart-chatbot-ui

**Comment by DiegoSpinola** [comment]
This one support openrouter and all it's models: https://github.com/SkylightAI/chatbot-ui

i've tried to reach @mckaywrigley on twitter to let him know about this fork wars (apparently he's planning on releasing a chatbot-ui v2 )  [check it out](https://twitter.com/mckaywrigley/status/1679966248212533249)

**Comment by oryan** [comment]
There will be a 2.0 version of this repo with a ton of new features released by the author in the next week or so.
It sounds like it will be a new repo though because it's a complete rewrite.

**Comment by JPDucky** [comment]
Would love an update

**Comment by redsonw** [comment]
> 这个 repo 的 2.0 版本将在未来一周左右发布大量新功能。听起来这将是一个新的回购，因为它是完全重写的。

Is this news reliable？

**Comment by oryan** [comment]
Was going off this tweet (xeet?)
But haven't seen anything since... :(

https://twitter.com/mckaywrigley/status/1679966248212533249?s=20

**Comment by Yonben** [comment]
@mckaywrigley any update for us? 🥺 🙏

**Comment by oryan** [comment]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/3709153/af68de06-871c-4b1a-81b6-512e6bb4a7d2)

https://twitter.com/mckaywrigley/status/1687255136048156672?s=46&t=Dy8OxvOaCFEOT3cqTyUXBA

**Comment by chokchai** [comment]
You guys should try https://github.com/Bin-Huang/chatbox until 2.0 come 
is an alternative and seems to update frequently.

**Comment by jorge-menjivar** [comment]
Everyone is welcome to use and improve my "fork". I decided to make it its own project since it has diverged so much from the original work. The main features are:

- New app router paradigm introduced in Next.js 13
- Multi-user Auth using NextAuth
- Cross-device sync using Supabase
- Support for 16k version of GPT 3.5, GPT 4 32k, etc.
- Support for Anthropic Claude models
- Support for Google Bard model
- Improved UI
- Multiple bug fixes

What I am working on:
- Support for any self-hosted model, like llama 2.
- Improve loading speeds

Known issues:
- Importing from Chatbot UI might not work.

https://github.com/jorge-menjivar/unSAGED

**Comment by ctrlbrk42** [comment]
@jorge-menjivar wow that is fantastic news.

**Comment by DiegoSpinola** [comment]
Hey @jorge-menjivar have you consider using the https://openrouter.ai/ abstraction layer ? if you did and decided against it why? thanks

**Comment by Jmackles** [comment]
> ![image](https://user-images.githubusercontent.com/3709153/258281732-af68de06-871c-4b1a-81b6-512e6bb4a7d2.png)
> 
> https://twitter.com/mckaywrigley/status/1687255136048156672?s=46&t=Dy8OxvOaCFEOT3cqTyUXBA

So in other words the OP is right and this repo has been totally abandoned in favor of a mythical app that only people who engage with him on twitter get beta access to and doesn't bother to fix any issues or answer questions with the first version, yet expects people to just trust them that the next version is even better-er?

**Comment by DiegoSpinola** [comment]
He seems new to the open software development practices ... Let's cut him some slack, but yes it does seem that this repo/version is abandoned for good...

**Comment by oryan** [comment]
@Jmackles He has stated on Twitter that he ended up doing a complete refactor and rather than make it harder for people who have been using this repo he opted to start a new one.

He has also stated that the 2.0 version will be open source and available on Github in it's own repo.

But honestly can you blame a guy for focusing on his own projects first? 
Also you don't have to engage with him, he has posted the link publicly for anyone to sign up and test.

takeoffchat.com

**Comment by Jmackles** [comment]
Yes he finally posted it yesterday. And I heard his reason, and it's clearly nonsense. "make it harder for people who have ben using this repo?" He's literally not updated this repo or responded to it at all in months. Twitter is not github. Not everyone wants to hang out on that cesspool of a platform. Regardless, this seems obvious that he took the gui he was working on and abandoned the original project in favor of creating a walled garden experience to monetize it for himself all while coasting on the success of the app he abandoned. If he didn't want to make it harder on the people using this repo, perhaps he could have acknowledged them literally at all?

By the way where is the repo for v2?  Is it open source? Cause it doesn't appear that way. So the original pull of the high quality initial repo that he abandoned is also gone, so you have to register on his website even to use it for free? And we're supposed to believe that this new version which again he jumped to completely abandoning and ignoring his original repo is worth at the best putting our personal information at risk and at worse paying $20 a month for software that we have no reason to believe he will fix because he never fixed or responded to issues about the first version. Of course I don't blame him for focusing on his own projects. This also was a project; but I can complain on the repo he abandoned and used the momentum of to better his personal station while pulling the ladder up with him and closing off the code "so to not make it harder for people who have been using this repo". That's such a contrived musk level reasoning for something so obviously demonstrably false. Just say that you wanted to move to developing full time and need to change repos. ON the repo. Not ghosting it and posting to people on twitter instead of the people asking on the actual repo about why he did it. Jesus christ. It's not like anyone wants the guy's firstborn. But you can't treat your users like this and expect them to just go buy your next project. Sorry.

**Comment by oryan** [comment]
@Jmackles who hurt you? 🤣
And more importantly why do you feel anyone owes you their code? It's weird.

Does it suck that this repo is abandoned? Yes.
But he didn't have to make it public in the first place. 
And he is not obligated to make any of his future work open either.

**Comment by Jmackles** [comment]
> @Jmackles who hurt you? 🤣 And more importantly why do you feel anyone owes you their code? It's weird.

You know what's really weird? How you are not able to actually answer me and instead have to resort to poking fun at how I said it. Anyone reading with half a brain will be able to make up their own mind entirely based off of the responses. It's like you're doing my arguing for me. Thanks!


> Does it suck that this repo is abandoned? Yes. But he didn't have to make it public in the first place. And he is not obligated to make any of his future work open either.

You're right, he's not, and users of the original aren't obligated to spend money on him either. But I'm seeing 2 threads on this abandoned repo citing leaked keys; do you believe he has any obligation to address major security issues with software that he abandoned? 

I ask you, exactly what constitutes somebody complaining using the proper channels? As opposed to providing updates to users outside of proper channels? Like, what would you consider to be enough of a big deal to raise frustrations? Would anything other than blatant fawning over chatui not suffice? So let me get this straight-pointing out legitimate frustrations on a repo issue that _I_ didn't even create, that's weird. Ignoring the issues section altogether and updating **only** twitter users who talk to him there as to why he hasn't touched it? Totally kosher.  Literally answer any of these questions, as I feel they are all legitimate, and tell me why I'm in the wrong for raising them:

1. How can anyone trust their api keys on the hosted app if there is no information on how they're stored, there's no repo, and the original app that he bases it off has open issues regarding api keys that have not beein addressed by the author?
2. Why does the author of the code not directly address issues on the repo, and why is it that you are the one delivering news about why he left the repo?
3. Where is the support for his v2 Chat UI coming from? Is it from this repo? See above then.

What you don't seem to be getting is that silence is the highest form of insult. In my opinion to abandon this repo and then not even actually update it whatsoever _**except of course when he updated the first line of his readme 2 days ago, while continuing to ignore repo issues**_ to link to his shiny new monetized version, is an insane waste of good will. If all he has supporting him from here on out are twitter blue subscribers, they deserve each other.

**Comment by Jmackles** [comment]
>And he is not obligated to make any of his future work open either.

Also, I need to point out that while you're right, one of the pulls that many have had for v1 was that it was a *very* good starting point and wasn't hosted. Other people are happy to take the v1 and run with it, mckay doesn't _**answer any fucking issues or questions about the repo though**_
