### ISSUE TITLE
Leaked key

### ISSUE THREAD

**Issue by Husky931** [mckaywrigley/chatbot-ui#944]
Starting somewhere from last week, there have been ongoing daily uses of the key generating anywhere from few dollars up to 10$.
I just saw another issue thread stating the same thing. 

Is there any way this can be fixed?

**Comment by seanchito** [comment]
Change your key, asap.   They got mine and immediately ran it up to the limit.  I think they are sharing the keys on discord.  FYI, OpenAI will cancel any billing for fraudulent usage, if you can get in touch with them, which is not easy.    Email support@openai.com.   The 'help center' is a complete black hole.   Customer service is not openai's strong suit.

The big question, so far unanswered, is if, and if so how, they are grabbing keys from chatbot-ui.   Where did McKay go?  He's been totally MIA here since April, even though he's all over twitter.   If keys are getting leaked from this app, it needs to be fixed immediately.

**Comment by signalprime** [comment]
any idea where this is happening in the code?  is it a bad NPM or is it something in this repository?

**Comment by kyleroberts-ai** [comment]
To clarify the app isn't "Leaking" the API key.

As you can see on docker: `https://hub.docker.com/search?q=chatbot-ui&source=community&sort=updated_at&order=desc`

A total of 91 'Chatbot-ui' repos have been added, many of these have multiple downloads.

This looks like a user error with not protecting the application with authentication or following steps to keep environment variables safe.

**Comment by auxon** [comment]
@signalprime  getServerSideProps ... "Note that irrespective of rendering type, any props will be passed to the page component and can be viewed on the client-side in the initial HTML. This is to allow the page to be [hydrated](https://react.dev/reference/react-dom/hydrate) correctly. Make sure that you don't pass any sensitive information that shouldn't be available on the client in props."

**Comment by GEMTechnologies** [comment]
@KyleRobertsAI I doubt whether it is user errors

**Comment by rudism** [comment]
My experience is the keys were leaked even when building my own docker image using the Dockerfile supplied in this repo, so I do not believe it can be attributed to malicious third party docker images. Additionally my chatbot-ui instance was only exposed on an internal network, meaning it's unlikely that the API key was scraped directly from the web interface via one of the environment variables being improperly exposed--it is my belief that something somewhere in the code is deliberately sending configured API keys (when configured via docker environment variables, at least) to a malicious third party.
