### ISSUE TITLE
Azure OpenAI - Unexpected token 'D', "[DONE]" is not valid JSON

### ISSUE THREAD

**Issue by GuganKailasam** [mckaywrigley/chatbot-ui#961]
I am getting the below error when using Azure OpenAI API keys.
Any idea on what could be the cause?

```
2023-09-04 15:40:09 SyntaxError: Unexpected token 'D', "[DONE]" is not valid JSON
2023-09-04 15:40:09     at JSON.parse (<anonymous>)
2023-09-04 15:40:09     at l (/app/.next/server/pages/api/chat.js:1:2537)
2023-09-04 15:40:09     at /app/.next/server/pages/api/chat.js:1:442
2023-09-04 15:40:09     at Object.feed (/app/.next/server/pages/api/chat.js:1:848)
2023-09-04 15:40:09     at Object.start (/app/.next/server/pages/api/chat.js:1:2718)
2023-09-04 15:40:09     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by GuganKailasam** [comment]
Related #580

**Comment by samo9789** [comment]
Thanks for pointing to the other ticket @GuganKailasam , I arrived on your issue through a google search and your comment pointed me to the fix.

**Comment by standaloneSA** [comment]
After implementing this fix, Azure API on GPT4 never completes. I tracked this back to an issue in utils/server/index.ts around line 96. 

The structure of the API response changes slightly. Instead of "finish_reason" (which is valid for GPT3.5T in Azure), GPT4 responds with 'finish_details' instead: 

{"id":"chatcmpl-8WsQI6EBge6RUh8D8cKUSqkqUXpcU","object":"chat.completion.chunk","created":1702846390,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":"stop","delta":{}}],"system_fingerprint":"fp_50a4261de5"}

vs

{"id":"chatcmpl-8WsS5A0CSGoUt4iI20SftgqDForNR","object":"chat.completion.chunk","created":1702846501,"model":"gpt-4","choices":[{"finish_details":{"type":"stop","stop":"<|fim_suffix|>"},"index":0,"delta":{}}]}


so the if statement needs modified slightly: 


              // 3.5 models
              if (json.choices[0].finish_reason != null) {
                controller.close();
                return;
              }
              // 4.0 models
              if (json.choices[0].finish_details != null) {
                controller.close();
                return;
              }
